function []=ShowImageSegmFcn(Inp)
%
%
if (nargin ~= 1),
   fprintf('ShowImageSegmFcn is called without argument\n');
   exit(1);
end;
%
if Inp ~= 0 
	handle_list = get(gcf,'userdata'); 
	if length(handle_list) > 0 
		h(1) = handle_list(1); 
		h(2) = handle_list(2); 
		h(3) = handle_list(3); 
		h(4) = handle_list(4); 
		h(5) = handle_list(5); 
		h(6) = handle_list(6); 
		txt1 = handle_list(7); 
		txt2 = handle_list(8); 
		txt3 = handle_list(9); 
		txt4 = handle_list(10); 
		txt5 = handle_list(11); 
		txt6 = handle_list(12); 
		txt7 = handle_list(13); 
		txt8 = handle_list(14); 
	end 
end 
%
if (Inp == 0),
   h_fig_orig=gcf;
   
%	figure('position',[ 360 543 560 420 ],'resize','on'); 
	figure('position',[ 290 543 640 450 ],'resize','on'); 
	set(gca,'visible','off');
	set(gcf,'Interruptible','yes'); 

	%  Uicontrol Object Creation 
	h(1) = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImageSegmFcn(1);',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Max',[ 1 ],... 
		'Min',[ 1 ],... 
		'Position',[ 0.03 0.39 0.035 0.22 ],... 
		'Enable','on',... 
		'String',' ',... 
		'Style','slider',... 
		'Units','normalized',... 
		'Value',[ 1 ],... 
		'Visible','on',... 
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','h(1)'); 
	h(2) = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImageSegmFcn(2);',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Max',[ 1 ],... 
		'Min',[ 0 ],... 
		'Position',[ 0.03 0.26 0.11 0.05 ],... 
		'Enable','on',... 
		'String','NEXT',... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Value',[ 0 ],... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','h(2)'); 
	h(3) = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImageSegmFcn(3);',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Max',[ 1 ],... 
		'Min',[ 0 ],... 
		'Position',[ 0.03 0.15 0.11 0.05 ],... 
		'Enable','on',... 
		'String','PREV',... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Value',[ 0 ],... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','h(3)'); 
	h(4) = uicontrol(... 
		'BackgroundColor',[ .7 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImageSegmFcn(4);',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Max',[ 1 ],... 
		'Min',[ 0 ],... 
		'Position',[ 0.03 0.05 0.11 0.05 ],... 
		'Enable','on',... 
		'String','EXIT',... 
		'Style','pushbutton',... 
		'Units','normalized',... 
		'Value',[ 0 ],... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','h(4)'); 
	h(5) = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImageSegmFcn(5);',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Max',[ 100 ],... 
		'Min',[ 1 ],... 
		'Position',[ 0.03 0.70 0.035 0.22 ],... 
		'Enable','on',... 
		'String',' ',... 
		'Style','slider',... 
		'Units','normalized',... 
		'Value',[ 50 ],... 
		'Visible','on',... 
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','h(5)'); 
	h(6) = uimenu(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'CallBack','ShowImageSegmFcn(6);',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Log',...
		'Accelerator','A',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'UserData',''); 
	  h6(1) = uimenu(h(6),... 
		  'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		  'CallBack','ShowImageSegmFcn(61);',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Log to file',...
		  'Clipping','on',... 
		  'Interruptible','no',... 
		  'UserData','h6(1)'); 
	  h6(2) = uimenu(h(6),... 
		  'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		  'CallBack','ShowImageSegmFcn(62);',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Stop logging',...
		  'Clipping','on',... 
		  'Interruptible','no',... 
		  'UserData','h6(2)'); 
		  

	 txt1 = uicontrol(... 
		'BackgroundColor',[ 0 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Position',[ 0.09 0.475 0.04 0.05 ],... 
		'String',num2str(round(get(h(1),'Value'))),... 
		'Style','text',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','txt1'); 
	 txt2 = uicontrol(... 
		'BackgroundColor',[ 0 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Position',[ 0.09 0.56 0.04 0.05 ],... 
		'String',num2str(get(h(1),'Max')),... 
		'Style','text',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','txt2'); 
	 txt3 = uicontrol(... 
		'BackgroundColor',[ 0 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Position',[ 0.09 0.39 0.04 0.05 ],... 
		'String',num2str(get(h(1),'Min')),... 
		'Style','text',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','txt3'); 
	 txt4 = uicontrol(... 
		'BackgroundColor',[ 0 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Position',[ 0.09 0.62 0.04 0.05 ],... 
		'String','No.',... 
		'Style','text',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','txt4'); 

	 txt5 = uicontrol(... 
		'BackgroundColor',[ 0 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Position',[ 0.09 0.785 0.04 0.05 ],... 
		'String',num2str(round(get(h(5),'Value'))),... 
		'Style','text',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','txt5'); 
	 txt6 = uicontrol(... 
		'BackgroundColor',[ 0 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Position',[ 0.09 0.87 0.04 0.05 ],... 
		'String',num2str(get(h(5),'Max')),... 
		'Style','text',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','txt6'); 
	 txt7 = uicontrol(... 
		'BackgroundColor',[ 0 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Position',[ 0.09 0.70 0.04 0.05 ],... 
		'String',num2str(get(h(5),'Min')),... 
		'Style','text',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','txt7'); 
	 txt8 = uicontrol(... 
		'BackgroundColor',[ 0 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Position',[ 0.09 0.93 0.04 0.05 ],... 
		'String','%',... 
		'Style','text',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','no',... 
		'Selected','off',... 
		'UserData','txt8'); 
		
	handle_ui_list = [ h(1) h(2) h(3) h(4) h(5), h(6),...
	                   txt1 txt2 txt3 txt4 txt5 txt6 txt7 txt8 ]; 

	handle_list = [handle_ui_list]; 
	set(gcf,'userdata',handle_list); 
	
   
   Name=get(h_fig_orig,'Name');

   if (Name ~= 0) & (Name ~= '')
   
      h_orig=get(h_fig_orig,'UserData');
      ImgNo = round(get(h_orig(1),'value'));
      Colormap=get(h_fig_orig,'Colormap');
      NoOfColors=length(Colormap);
   
      [pre,dim,siz,limits,scale]=ReadAnalyzeHdr(Name);
      %
      img=ReadAnalyzeImg(Name,dim,pre,limits,ImgNo);    
      if (img ~= []),
         MaxPix=max(max(img));
         MinPix=min(min(img));
         if ((MaxPix ~= 0) | (MinPix ~= 0))
            colors=get(gcf,'Colormap');
            [NoOfColors,dummy]=size(colors);

            if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
               img=(img-limits(2))*(NoOfColors/(limits(1)-limits(2)));
            else
               limits=limits*scale;
               img=(img*scale-limits(2))*(NoOfColors/(limits(1)-limits(2)));
            end;   
         else
            fprintf('All pixels zero\n');   
         end; 

         if (isstr(get(gca,'UserData'),'ImageSegmObject')) == 1) &...
	       (strcmp(get(gca,'UserData'),'ImageSegmObject') ~= 1)
            axes('position',[0.2 0.1 0.75 0.8],'DrawMode','fast');
         end;
         
         % Threshold image
         ThresLevel = get(h(5),'Value');
         % MaxImg=max(max(img));
         MaxImg=limits(1);
         ThresVal=ThresLevel/100*MaxImg;
         Index=find(img<ThresVal);
         img(Index)=zeros(length(Index),1);

         hi=image(rot90(img));

         set(hi,'UserData',[limits(2) limits(1)]);   

         set(gca,'UserData','ImageObject','TickDir','out','FontName','Times');
         axis('image');

         set(gcf,'NextPlot','add');
         set(gcf,'Colormap',Colormap);
         set(gcf,'Name',Name);
         colorbar
      else
         fprintf('No data in choosen image file (%s)\n',ImageName);   
      end;
   
      set(h(1),'Max',dim(3));
      set(txt2,'String',num2str(dim(3)),'UserData',num2str(dim(3)));
      set(txt1,'string',num2str(round(ImgNo))); 
      set(h(1),'value',round(ImgNo)); 

      set(gca,'Visible','off');
      
      % Start choosing ROI's
      ShowImageSegmCalc(0);	

   else
      fprintf('No original image file choosen (can not segment)\n');   
   end;   

elseif Inp == 1 		  
        set(h,'ButtonDownFcn','');  
        
	% disp('h(1) selected.') 
	ImgNo = round(get(h(1),'value'));
	set(txt1,'string',num2str(ImgNo)); 

	ImageName = get(gcf,'name');
        if (ImageName == []),
           fprintf('No image file selected\n');
        else   
           [precision,dim,siz,limits,scale]=ReadAnalyzeHdr(ImageName);
           img=ReadAnalyzeImg(ImageName,dim,precision,limits,ImgNo);
           if (img ~= []),
	      hhh=get(gca,'Children');
	      hh_image=-1;
	      for ii=1:length(hhh),
	         if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	            hh_image=hhh(ii);
	         end;   
	      end;
	      
	      if (hh_image ~= -1),
                 MaxPix=max(max(img));
                 MinPix=min(min(img));
                 if ((MaxPix ~= 0) | (MinPix ~= 0))
                    colors=get(gcf,'Colormap');
                    [NoOfColors,dummy]=size(colors);
                    ImgLimits=get(hh_image,'UserData');
                    
                    if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                       img=(img-ImgLimits(1))*...
                            (NoOfColors/(ImgLimits(2)-ImgLimits(1)));
                    else
                       img=(img*scale-ImgLimits(1))*...
                            (NoOfColors/(ImgLimits(2)-ImgLimits(1)));
                    end;   
                 else
                    fprintf('All pixels zero\n');   
                 end;
                    
                 % Threshold image
                 ThresLevel = get(h(5),'Value');
                 % MaxImg=max(max(img));
                 MaxImg=ImgLimits(2);
                 ThresVal=ThresLevel/100*MaxImg;
                 Index=find(img<ThresVal);
                 img(Index)=zeros(length(Index),1);

                 set(hh_image,'CData',rot90(img));
              end;   
           else
              fprintf('No data in choosen image file \n');   
           end;
        end;   
elseif Inp == 2 
        set(h,'ButtonDownFcn','');  
        
	% disp('h(2) selected.') 
	ImgNo = round(get(h(1),'value'));
	ImgNo = ImgNo + 1;
	if ImgNo > get(h(1),'Max')
	   ImgNo = get(h(1),'Max');
	end;   
	set(txt1,'string',num2str(ImgNo)); 
	set(h(1),'value',ImgNo); 

	ImageName = get(gcf,'name');
        if (ImageName == []),
           fprintf('No image file selected\n');
        else   
           [precision,dim,siz,limits,scale]=ReadAnalyzeHdr(ImageName);
           img=ReadAnalyzeImg(ImageName,dim,precision,limits,ImgNo);
           if (img ~= []),
	      hhh=get(gca,'Children');
	      hh_image=-1;
	      for ii=1:length(hhh),
	         if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	            hh_image=hhh(ii);
	         end;   
	      end;
	      
	      if (hh_image ~= -1),
                 MaxPix=max(max(img));
                 MinPix=min(min(img));
                 if ((MaxPix ~= 0) | (MinPix ~= 0))
                    colors=get(gcf,'Colormap');
                    [NoOfColors,dummy]=size(colors);
                    ImgLimits=get(hh_image,'UserData');
                    
                    if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                       img=(img-ImgLimits(1))*...
                            (NoOfColors/(ImgLimits(2)-ImgLimits(1)));
                    else
                       img=(img*scale-ImgLimits(1))*...
                            (NoOfColors/(ImgLimits(2)-ImgLimits(1)));
                    end;   
                 else
                    fprintf('All pixels zero\n');   
                 end;   

                 % Threshold image
                 ThresLevel = get(h(5),'Value');
                 % MaxImg=max(max(img));
                 MaxImg=ImgLimits(2);
                 ThresVal=ThresLevel/100*MaxImg;
                 Index=find(img<ThresVal);
                 img(Index)=zeros(length(Index),1);

                 set(hh_image,'CData',rot90(img));
              end;   
           else
              fprintf('No data in choosen image file\n');   
           end;
        end;   
elseif Inp == 3 
        set(h,'ButtonDownFcn','');  
        
	% disp('h(3) selected.') 
	ImgNo = round(get(h(1),'value'));
	ImgNo = ImgNo - 1;
	if ImgNo < get(h(1),'Min')
	   ImgNo = get(h(1),'Min');
	end;   
	set(txt1,'string',num2str(ImgNo)); 
	set(h(1),'value',ImgNo); 

	ImageName = get(gcf,'name');
        if (ImageName == []),
           fprintf('No image file selected\n');
        else   
           [precision,dim,siz,limits,scale]=ReadAnalyzeHdr(ImageName);
           img=ReadAnalyzeImg(ImageName,dim,precision,limits,ImgNo);
           if (img ~= []),
	      hhh=get(gca,'Children');
	      hh_image=-1;
	      for ii=1:length(hhh),
	         if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	            hh_image=hhh(ii);
	         end;   
	      end;
	      
	      if (hh_image ~= -1),
                 MaxPix=max(max(img));
                 MinPix=min(min(img));
                 if ((MaxPix ~= 0) | (MinPix ~= 0))
                    colors=get(gcf,'Colormap');
                    [NoOfColors,dummy]=size(colors);
                    ImgLimits=get(hh_image,'UserData');
                    
                    if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                       img=(img-ImgLimits(1))*...
                            (NoOfColors/(ImgLimits(2)-ImgLimits(1)));
                    else
                       img=(img*scale-ImgLimits(1))*...
                            (NoOfColors/(ImgLimits(2)-ImgLimits(1)));
                    end;   
                 else
                    fprintf('All pixels zero\n');   
                 end;   

                 % Threshold image
                 ThresLevel = get(h(5),'Value');
                 % MaxImg=max(max(img));
                 MaxImg=ImgLimits(2);
                 ThresVal=ThresLevel/100*MaxImg;
                 Index=find(img<ThresVal);
                 img(Index)=zeros(length(Index),1);

                 set(hh_image,'CData',rot90(img));
              end;   
           else
              fprintf('No data in choosen image file\n');   
           end;
        end;   
elseif Inp == 4 
        % exit
        close(gcf);
	% disp('h(4) selected.') 
elseif Inp == 5 
	% disp('h(5) selected.') 
	ThresLevel = round(get(h(5),'value'));
	set(txt5,'string',num2str(round(ThresLevel)));
	ImgNo = round(get(h(1),'value'));
	 
	ImageName = get(gcf,'name');
        if (ImageName == []),
           fprintf('No image file selected\n');
        else   
           [precision,dim,siz,limits,scale]=ReadAnalyzeHdr(ImageName);
           img=ReadAnalyzeImg(ImageName,dim,precision,limits,ImgNo);
           if (img ~= []),
	      hhh=get(gca,'Children');
	      hh_image=-1;
	      for ii=1:length(hhh),
	         if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	            hh_image=hhh(ii);
	         end;   
	      end;
	      
	      if (hh_image ~= -1),
                 MaxPix=max(max(img));
                 MinPix=min(min(img));
                 if ((MaxPix ~= 0) | (MinPix ~= 0))
                    colors=get(gcf,'Colormap');
                    [NoOfColors,dummy]=size(colors);
                    ImgLimits=get(hh_image,'UserData');
                    
                    if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                       img=(img-ImgLimits(1))*...
                            (NoOfColors/(ImgLimits(2)-ImgLimits(1)));
                    else
                       img=(img*scale-ImgLimits(1))*...
                            (NoOfColors/(ImgLimits(2)-ImgLimits(1)));
                    end;   
                 else
                    fprintf('All pixels zero\n');   
                 end;   

                 % Threshold image
                 ThresLevel = get(h(5),'Value');
                 % MaxImg=max(max(img));
                 MaxImg=ImgLimits(2);
                 ThresVal=ThresLevel/100*MaxImg;
                 Index=find(img<ThresVal);
                 img(Index)=zeros(length(Index),1);

                 set(hh_image,'CData',rot90(img));
              end;   
           else
              fprintf('No data in choosen image file\n');   
           end;
        end;   
	
elseif Inp == 6 
	% disp('h(6) selected.') 
elseif Inp == 61 
	% disp('h6(1) selected.') 
        [StatFileName, StatFilePath] = uigetfile('*.stat',...
                    'ROI statistics file name');
        
        if (length(StatFileName) == 0)
           StatFileName='RoiStatistics.stat';
        end;   
        if (strfind(StatFileName,'.stat') == [])
           StatFileName=[StatFileName '.stat']; 
        end;          
	
        set(h(6),'UserData',[StatFilePath StatFileName]);
elseif Inp == 62 
	% disp('h6(2) selected.') 
	
        set(h(6),'UserData','');
else
   fprintf('ShowImageSegmFcn no legal input to fcn\n');
end;     
