function ShowImage(command,param1) 
%  Template for uicontrol form. 
%   
%  1. Optional: Replace all occurances of 'ShowImage' with desired 'filename'. 
%  2. Optional: Resave this file as that 'filename'. 
%  3. Optional: Fill in the 'elseif command == ...' sections with 
%          code that does something other than display which 
%          uicontrol button was pressed. Be creative! 
%  4. Optional: Change each 'h(index)' ,where index is 1,2,3,.. 
%               to a functionally more descriptive name. 
%  5. Optional: Delete these first 10 comment lines. 
%   
%  ShowImage.m 
%   
%  usage:       ShowImage(command,parameter1) 
%   
%           where 
%   
%               'command' is used to perform some defined operation 
%               'parameter1' can be used pass extra information 
%                              to a defined operation 
%   
%           If no arguements are used the GUI is initialized. 
%   
%   
%  Created: 12-Apr-94 
%  Using  : guimaker by Patrick Marchand 
%                         (pmarchan@motown.ge.com) 
%  Author :  
%  Mods.  :  
%   

%  Copyright (c) 1994 by Patrick Marchand 
%       Permission is granted to modify and re-distribute this 
%	code in any manner as long as this notice is preserved. 
%	All standard disclaimers apply. 

if nargin == 0 
	command = 'new'; 
end 

if isstr(command) 
	if strcmp(lower(command),'initialize') | strcmp(lower(command),'new') 
		command = 0; 
	elseif strcmp(lower(command),lower('h(1)')) 
		command = 1; 
	elseif strcmp(lower(command),lower('h(2)')) 
		command = 2; 
	elseif strcmp(lower(command),lower('h(3)')) 
		command = 3; 
	elseif strcmp(lower(command),lower('h(4)')) 
		command = 4; 
	elseif strcmp(lower(command),lower('h(5)')) 
		command = 5; 
	elseif strcmp(lower(command),lower('h5(1)')) 
		command = 51; 
	elseif strcmp(lower(command),lower('h(6)')) 
		command = 6; 
	elseif strcmp(lower(command),lower('h6(1)')) 
		command = 61; 
	elseif strcmp(lower(command),lower('h6(2)')) 
		command = 62; 
	elseif strcmp(lower(command),lower('h6(3)')) 
		command = 63; 
	elseif strcmp(lower(command),lower('h6(4)')) 
		command = 64; 
	elseif strcmp(lower(command),lower('h6(5)')) 
		command = 65; 
	elseif strcmp(lower(command),lower('h(7)')) 
		command = 7; 
	elseif strcmp(lower(command),lower('h7(1)')) 
		command = 71; 
	elseif strcmp(lower(command),lower('h7(2)')) 
		command = 72; 
	elseif strcmp(lower(command),lower('h7(3)')) 
		command = 73; 
	elseif strcmp(lower(command),lower('h7(4)')) 
		command = 74; 
	elseif strcmp(lower(command),lower('h7(5)')) 
		command = 75; 
	elseif strcmp(lower(command),lower('h7(6)')) 
		command = 76; 
	elseif strcmp(lower(command),lower('h(8)')) 
		command = 8; 
	elseif strcmp(lower(command),lower('h8(1)')) 
		command = 81; 
	elseif strcmp(lower(command),lower('h8(2)')) 
		command = 82; 
	elseif strcmp(lower(command),lower('h8(3)')) 
		command = 83; 
	elseif strcmp(lower(command),lower('h8(4)')) 
		command = 84; 
	elseif strcmp(lower(command),lower('h8(5)')) 
		command = 85; 
	elseif strcmp(lower(command),lower('h(9)')) 
		command = 9; 
	elseif strcmp(lower(command),lower('h9(1)')) 
		command = 91; 
	elseif strcmp(lower(command),lower('h9(2)')) 
		command = 92; 
	elseif strcmp(lower(command),lower('h9(3)')) 
		command = 93; 
	elseif strcmp(lower(command),lower('h9(4)')) 
		command = 94; 
	elseif strcmp(lower(command),lower('h9(5)')) 
		command = 95; 
	elseif strcmp(lower(command),lower('h9(6)')) 
		command = 96; 
	elseif strcmp(lower(command),lower('h9(7)')) 
		command = 97; 
	elseif strcmp(lower(command),lower('h9(8)')) 
		command = 98; 
	elseif strcmp(lower(command),lower('h9(9)')) 
		command = 99; 
	elseif strcmp(lower(command),lower('h9(10)')) 
		command = 910; 
	elseif strcmp(lower(command),lower('h9(11)')) 
		command = 911; 
	elseif strcmp(lower(command),lower('h9(12)')) 
		command = 912; 
	elseif strcmp(lower(command),lower('h(10)')) 
		command = 10; 
	elseif strcmp(lower(command),lower('h10(1)')) 
		command = 101; 
	elseif strcmp(lower(command),lower('h10(2)')) 
		command = 102; 
	elseif strcmp(lower(command),lower('h10(3)')) 
		command = 103; 
	elseif strcmp(lower(command),lower('h(11)')) 
		command = 11; 
	elseif strcmp(lower(command),lower('h11(1)')) 
		command = 111; 
	elseif strcmp(lower(command),lower('h11(2)')) 
		command = 112; 
	elseif strcmp(lower(command),lower('h11(3)')) 
		command = 113; 
	elseif strcmp(lower(command),lower('h(12)')) 
		command = 12; 
	elseif strcmp(lower(command),lower('h12(1)')) 
		command = 121; 
	elseif strcmp(lower(command),lower('h(13)')) 
		command = 13; 
	elseif strcmp(lower(command),lower('h13(1)')) 
		command = 131; 
	elseif strcmp(lower(command),lower('h(14)')) 
		command = 14; 
	elseif strcmp(lower(command),lower('h14(1)')) 
		command = 141; 
	elseif strcmp(lower(command),lower('h(15)')) 
		command = 15; 
	end 
end 

if command ~= 0 
	handle_list = get(gcf,'userdata'); 
	if length(handle_list) > 0 
		h(1) = handle_list(1); 
		h(2) = handle_list(2); 
		h(3) = handle_list(3); 
		h(4) = handle_list(4); 
		h(5) = handle_list(5); 
		h(6) = handle_list(6); 
		h(7) = handle_list(7); 
		h(8) = handle_list(8); 
		h(9) = handle_list(9); 
		h(10) = handle_list(10); 
		h(11) = handle_list(11); 
		h(12) = handle_list(12); 
		h(13) = handle_list(13); 
		h(14) = handle_list(14); 
		h(15) = handle_list(15); 
		txt1 = handle_list(16); 
		txt2 = handle_list(17); 
		txt3 = handle_list(18); 
		txt4 = handle_list(19); 
		txt5 = handle_list(20); 
		txt6 = handle_list(21); 
		txt7 = handle_list(22); 
		txt8 = handle_list(23); 
	end 
end 


if command == 0 
%	figure('position',[ 360 543 560 420 ],'resize','on'); 
	figure('position',[ 290 543 640 450 ],'resize','on'); 
	set(gca,'visible','off');
	set(gcf,'Interruptible','on'); 

	%  Uicontrol Object Creation 
	h(1) = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImage(''h(1)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Max',[ 1+1e-6 ],... 
		'Min',[ 1 ],... 
		'Units','normalized',... 
		'Position',[ 0.03 0.39 0.015 0.22 ],... 
		'Enable','on',... 
		'String',' ',... 
		'Style','slider',... 
		'Value',[ 1 ],... 
		'Visible','on',... 
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','h(1)'); 
	h(2) = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImage(''h(2)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Max',[ 1 ],... 
		'Min',[ 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.03 0.26 0.11 0.05 ],... 
		'Enable','on',... 
		'String','NEXT',... 
		'Style','pushbutton',... 
		'Value',[ 0 ],... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','h(2)'); 
	h(3) = uicontrol(... 
		'BackgroundColor',[ 0.7 0.7 0.7 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImage(''h(3)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Max',[ 1 ],... 
		'Min',[ 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.03 0.15 0.11 0.05 ],... 
		'Enable','on',... 
		'String','PREV',... 
		'Style','pushbutton',... 
		'Value',[ 0 ],... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','h(3)'); 
	h(4) = uicontrol(... 
		'BackgroundColor',[ .7 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImage(''h(4)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Max',[ 1 ],... 
		'Min',[ 0 ],... 
		'Units','normalized',... 
		'Position',[ 0.03 0.05 0.11 0.05 ],... 
		'Enable','on',... 
		'String','EXIT',... 
		'Style','pushbutton',... 
		'Value',[ 0 ],... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','h(4)'); 
	h(5) = uimenu(... 
		'CallBack','ShowImage(''h(5)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Load',...
		'Accelerator','L',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'UserData','h(5)'); 
	  h5(1) = uimenu(h(5),... 
		  'CallBack','ShowImage(''h5(1)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Load',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h5(1)'); 
	h(6) = uimenu(... 
		'CallBack','ShowImage(''h(6)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Layout',...
		'Accelerator','L',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'UserData','h(6)'); 
	  h6(1) = uimenu(h(6),... 
		  'CallBack','ShowImage(''h6(1)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Axis',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h6(1)'); 
	    h61(1) = uimenu(h6(1),... 
		    'CallBack','ShowImage(''h6(1)'',1);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','ON',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h61(1)'); 
	    h61(2) = uimenu(h6(1),... 
		    'CallBack','ShowImage(''h6(1)'',2);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','OFF',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h61(2)'); 
	  h6(2) = uimenu(h(6),... 
		  'CallBack','ShowImage(''h6(2)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Marker',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h6(2)'); 
	    h62(1) = uimenu(h6(2),... 
		    'CallBack','ShowImage(''h6(2)'',1);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','ON',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h62(1)'); 
	    h62(2) = uimenu(h6(2),... 
		    'CallBack','ShowImage(''h6(2)'',2);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','OFF',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h62(2)'); 
	  h6(3) = uimenu(h(6),... 
		  'CallBack','ShowImage(''h6(3)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Color',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h6(3)'); 
	    h63(1) = uimenu(h6(3),... 
		    'CallBack','ShowImage(''h6(3)'',1);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','UCLA',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h63(1)'); 
	    h63(2) = uimenu(h6(3),... 
		    'CallBack','ShowImage(''h6(3)'',2);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','GRAY',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h63(2)'); 
	    h63(3) = uimenu(h6(3),... 
		    'CallBack','ShowImage(''h6(3)'',3);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','HSV',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h63(3)'); 
	    h63(4) = uimenu(h6(3),... 
		    'CallBack','ShowImage(''h6(3)'',4);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','HOT',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h63(4)'); 
	    h63(5) = uimenu(h6(3),... 
		    'CallBack','ShowImage(''h6(3)'',5);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','COOL',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h63(5)'); 
	    h63(6) = uimenu(h6(3),... 
		    'CallBack','ShowImage(''h6(3)'',6);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','PINK',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h63(6)'); 
	    h63(7) = uimenu(h6(3),... 
		    'CallBack','ShowImage(''h6(3)'',7);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','INVERT',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h63(7)'); 
	  h6(4) = uimenu(h(6),... 
		  'CallBack','ShowImage(''h6(4)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Control',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h6(4)'); 
	    h64(1) = uimenu(h6(4),... 
		    'CallBack','ShowImage(''h6(4)'',1);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','ON',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h64(1)'); 
	    h64(2) = uimenu(h6(4),... 
		    'CallBack','ShowImage(''h6(4)'',2);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','OFF',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h64(2)'); 
	  h6(5) = uimenu(h(6),... 
		  'CallBack','ShowImage(''h6(5)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Colorbar',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h6(5)'); 
	    h65(1) = uimenu(h6(5),... 
		    'CallBack','ShowImage(''h6(5)'',1);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','Max',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h65(1)'); 
	    h65(2) = uimenu(h6(5),... 
		    'CallBack','ShowImage(''h6(5)'',2);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','Min',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h65(2)'); 
	h(7) = uimenu(... 
		'CallBack','ShowImage(''h(7)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Text',...
		'Accelerator','T',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'UserData','h(7)'); 
	  h7(1) = uimenu(h(7),... 
		  'CallBack','ShowImage(''h7(1)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Write',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h7(1)'); 
	  h7(2) = uimenu(h(7),... 
		  'CallBack','ShowImage(''h7(2)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Size',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','OFF'); 
	    h72(1) = uimenu(h7(2),... 
		    'CallBack','ShowImage(''h7(2)'',1);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','8',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h72(1)'); 
	    h72(2) = uimenu(h7(2),... 
		    'CallBack','ShowImage(''h7(2)'',2);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','12',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h72(2)'); 
	    h72(3) = uimenu(h7(2),... 
		    'CallBack','ShowImage(''h7(2)'',3);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','24',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h72(3)'); 
	    h72(4) = uimenu(h7(2),... 
		    'CallBack','ShowImage(''h7(2)'',4);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','Other',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h72(4)'); 
	  h7(3) = uimenu(h(7),... 
		  'CallBack','ShowImage(''h7(3)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Font',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','Helvetica'); 
	    h73(1) = uimenu(h7(3),... 
		    'CallBack','ShowImage(''h7(3)'',1);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','Helvetica',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h73(1)'); 
	    h73(2) = uimenu(h7(3),... 
		    'CallBack','ShowImage(''h7(3)'',2);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','Times',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h73(2)'); 
	    h73(3) = uimenu(h7(3),... 
		    'CallBack','ShowImage(''h7(3)'',3);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','Courier',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h73(3)'); 
	    h73(4) = uimenu(h7(3),... 
		    'CallBack','ShowImage(''h7(3)'',4);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','Symbol',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h73(4)'); 
	  h7(4) = uimenu(h(7),... 
		  'CallBack','ShowImage(''h7(4)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Color',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','white'); 
	    h74(1) = uimenu(h7(4),... 
		    'CallBack','ShowImage(''h7(4)'',1);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','white',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h74(1)'); 
	    h74(2) = uimenu(h7(4),... 
		    'CallBack','ShowImage(''h7(4)'',2);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','red',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h74(2)'); 
	    h74(3) = uimenu(h7(4),... 
		    'CallBack','ShowImage(''h7(4)'',3);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','yellow',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h74(3)'); 
	    h74(4) = uimenu(h7(4),... 
		    'CallBack','ShowImage(''h7(4)'',4);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','green',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h74(4)'); 
	    h74(5) = uimenu(h7(4),... 
		    'CallBack','ShowImage(''h7(4)'',5);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','blue',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h74(5)'); 
	  h7(5) = uimenu(h(7),... 
		  'CallBack','ShowImage(''h7(5)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Move',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','OFF'); 
	  h7(6) = uimenu(h(7),... 
		  'CallBack','ShowImage(''h7(6)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Delete',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','OFF'); 
	h(8) = uimenu(... 
		'CallBack','ShowImage(''h(8)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Print',...
		'Accelerator','P',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'UserData','h(8)'); 
	  h8(1) = uimenu(h(8),... 
		  'CallBack','ShowImage(''h8(1)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Laserprinter',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h8(1)'); 
	  h8(2) = uimenu(h(8),... 
		  'CallBack','ShowImage(''h8(2)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Paintjet',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h8(2)'); 
	  h8(3) = uimenu(h(8),... 
		  'CallBack','ShowImage(''h8(3)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Tiff image',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h8(3)'); 
	  h8(4) = uimenu(h(8),... 
		  'CallBack','ShowImage(''h8(4)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','EPS image',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h8(4)'); 
	  h8(5) = uimenu(h(8),... 
		  'CallBack','ShowImage(''h8(5)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Tiff image (all)',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h8(5)'); 
	h(9) = uimenu(... 
		'CallBack','ShowImage(''h(9)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Roi',...
		'Accelerator','R',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'UserData','h(9)'); 
	  h9(1) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(1)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Create',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(1)'); 
	  h9(2) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(2)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Filter outside',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(2)'); 
	  h9(3) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(3)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Filter inside',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(3)'); 
	  h9(4) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(4)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','BW one inside',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(4)'); 
	  h9(5) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(5)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','BW zero inside',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(5)'); 
	  h9(6) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(6)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Save img',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(6)'); 
	  h9(7) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(7)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Filter/save all',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(7)'); 
	  h9(8) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(8)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Dynamic ROI curve',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(8)'); 
	  h9(9) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(9)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Delete',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(9)'); 
	  h9(10) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(10)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Mean/Std',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(10)'); 
	  h9(11) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(11)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Save',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(11)'); 
	  h9(12) = uimenu(h(9),... 
		  'CallBack','ShowImage(''h9(12)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Load',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h9(12)'); 
	h(10) = uimenu(... 
		'CallBack','ShowImage(''h(10)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Filter',...
		'Accelerator','F',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'UserData','h(10)'); 
	  h10(1) = uimenu(h(10),... 
		  'CallBack','ShowImage(''h10(1)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Hanning',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h10(1)'); 
	    h101(1) = uimenu(h10(1),... 
		    'CallBack','ShowImage(''h10(1)'',4);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','4 units',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h101(1)'); 
	    h101(2) = uimenu(h10(1),... 
		    'CallBack','ShowImage(''h10(1)'',8);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','8 units',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h101(2)'); 
	    h101(3) = uimenu(h10(1),... 
		    'CallBack','ShowImage(''h10(1)'',20);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','20 units',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h101(3)'); 
	    h101(4) = uimenu(h10(1),... 
		    'CallBack','ShowImage(''h10(1)'',0);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','other',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h101(4)'); 
	  h10(2) = uimenu(h(10),... 
		  'CallBack','ShowImage(''h10(2)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Gauss',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h10(2)'); 
	    h102(1) = uimenu(h10(2),... 
		    'CallBack','ShowImage(''h10(2)'',4);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','4 units',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h102(1)'); 
	    h102(2) = uimenu(h10(2),... 
		    'CallBack','ShowImage(''h10(2)'',8);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','8 units',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h102(2)'); 
	    h102(3) = uimenu(h10(2),... 
		    'CallBack','ShowImage(''h10(2)'',20);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','20 units',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h102(3)'); 
	    h102(4) = uimenu(h10(2),... 
		    'CallBack','ShowImage(''h10(2)'',0);',... 
		    'ForegroundColor',[ 0 0 0 ],... 
		    'Enable','on',... 
		    'Visible','on',... 
		    'Label','other',...
		    'Clipping','on',... 
		    'Interruptible','off',... 
		    'UserData','h102(4)'); 
	  h10(3) = uimenu(h(10),... 
		  'CallBack','ShowImage(''h10(3)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Filter all',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h10(3)'); 
	h(11) = uimenu(... 
		'CallBack','ShowImage(''h(11)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Cut',...
		'Accelerator','C',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'UserData','h(11)'); 
	  h11(1) = uimenu(h(11),... 
		  'CallBack','ShowImage(''h11(1)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Sagital/Coronal',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h11(1)'); 
	  h11(2) = uimenu(h(11),... 
		  'CallBack','ShowImage(''h11(2)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Print in tiff file',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h11(2)'); 
	  h11(3) = uimenu(h(11),... 
		  'CallBack','ShowImage(''h11(3)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Print in eps file',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h11(3)'); 
	h(12) = uimenu(... 
		'CallBack','ShowImage(''h(12)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Segment',...
		'Accelerator','S',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'UserData','h(12)'); 
	  h12(1) = uimenu(h(12),... 
		  'CallBack','ShowImage(''h12(1)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Segmentation',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h12(1)'); 
	h(13) = uimenu(... 
		'CallBack','ShowImage(''h(13)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Montage',...
		'Accelerator','M',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'UserData','h(13)'); 
	  h13(1) = uimenu(h(13),... 
		  'CallBack','ShowImage(''h13(1)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Show',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h13(1)'); 
	h(14) = uimenu(... 
		'CallBack','ShowImage(''h(14)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Label','Fusion',...
		'Accelerator','F',...
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'UserData','h(14)'); 
	  h14(1) = uimenu(h(14),... 
		  'CallBack','ShowImage(''h14(1)'');',... 
		  'ForegroundColor',[ 0 0 0 ],... 
		  'Enable','on',... 
		  'Visible','on',... 
		  'Label','Show',...
		  'Clipping','on',... 
		  'Interruptible','off',... 
		  'UserData','h14(1)'); 
	h(15) = uicontrol(... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImage(''h(15)'');',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Max',[ 1+1e-6 ],... 
		'Min',[ 1 ],... 
		'Units','normalized',... 
		'Position',[ 0.09 0.39 0.015 0.22 ],... 
		'Enable','on',... 
		'String',' ',... 
		'Style','slider',... 
		'Value',[ 1 ],... 
		'Visible','on',... 
		'ButtonDownFcn','',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','h(15)'); 

%		'BackgroundColor',[ 0 0 0 ],...
         BGC=get(gcf,'Color');        
	 txt1 = uicontrol(... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Units','normalized',... 
		'Position',[ 0.044 0.48 0.046 0.04 ],... 
		'String',num2str(round(get(h(1),'Value'))),... 
		'Style','text',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','txt1',...
                'FontSize',9,...
                'BackgroundColor',BGC,...
                'ForegroundColor','black'); 
	 txt2 = uicontrol(... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Units','normalized',... 
		'Position',[ 0.044 0.57 0.046 0.04 ],... 
		'String',num2str(get(h(1),'Max')),... 
		'Style','text',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','txt2',...
                'FontSize',9,...
                'BackgroundColor',BGC,...
                'ForegroundColor','black'); 
	 txt3 = uicontrol(... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Units','normalized',... 
		'Position',[ 0.044 0.39 0.046 0.04 ],... 
		'String',num2str(get(h(1),'Min')),... 
		'Style','text',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','txt3',...
                'FontSize',9,...
                'BackgroundColor',BGC,...
                'ForegroundColor','black'); 
	 txt4 = uicontrol(... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Units','normalized',... 
		'Position',[ 0.025 0.62 0.04 0.05 ],... 
		'String','Sl.',... 
		'Style','text',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','txt4',...
                'FontSize',9,...
                'BackgroundColor',BGC,...
                'ForegroundColor','black'); 
	 txt5 = uicontrol(... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Units','normalized',... 
		'Position',[ 0.105 0.48 0.046 0.04 ],... 
		'String',num2str(round(get(h(15),'Value'))),... 
		'Style','text',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','txt5',...
                'FontSize',9,...
                'BackgroundColor',BGC,...
                'ForegroundColor','black'); 
	 txt6 = uicontrol(... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Units','normalized',... 
		'Position',[ 0.105 0.57 0.046 0.04 ],... 
		'String',num2str(get(h(15),'Max')),... 
		'Style','text',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','txt6',...
                'FontSize',9,...
                'BackgroundColor',BGC,...
                'ForegroundColor','black'); 
	 txt7 = uicontrol(... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Units','normalized',... 
		'Position',[ 0.105 0.39 0.046 0.04 ],... 
		'String',num2str(get(h(15),'Min')),... 
		'Style','text',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','txt7',...
                'FontSize',9,...
                'BackgroundColor',BGC,...
                'ForegroundColor','black'); 
	 txt8 = uicontrol(... 
		'ButtonDownFcn','',... 
		'CallBack','',... 
		'ForegroundColor',[ 1 1 1 ],... 
		'HorizontalAlignment','center',... 
		'Units','normalized',... 
		'Position',[ 0.09 0.62 0.04 0.05 ],... 
		'String','Fr.',... 
		'Style','text',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'UserData','txt8',...
                'FontSize',9,...
                'BackgroundColor',BGC,...
                'ForegroundColor','black'); 
		
	handle_ui_list = [ h(1) h(2) h(3) h(4) h(5) h(6) h(7) h(8) h(9),...
	                   h(10) h(11) h(12) h(13) h(14), h(15)...
			   txt1 txt2 txt3 txt4 txt5 txt6 txt7 txt8]; 

	handle_list = [handle_ui_list]; 
	set(gcf,'userdata',handle_list); 


elseif command == 1 
	% disp('h(1) selected.') 
	ImgNo = round(get(h(1),'value'));
	set(txt1,'string',num2str(ImgNo)); 

	FrameNo = round(get(h(15),'value'));

	ImageName = get(gcf,'name');
        if (isempty(ImageName)),
           fprintf('No image file selected\n');
        else   
           [precision,dim,siz,limits,scale,offset]=ReadAnalyzeHdr(ImageName);
           img=ReadAnalyzeImg(ImageName,dim,precision,limits,[ImgNo FrameNo]);
           if (~isempty(img)),
	      hhh=get(gca,'Children');
	      hh_image=-1;
	      for ii=1:length(hhh),
	         if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	            hh_image=hhh(ii);
	         end;   
	      end;
	      
	      if (hh_image ~= -1),
                 if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                    img=img;
		 else
                    img=img*scale-offset;
	         end;   
                 set(hh_image,'CData',rot90(img));
              end;   
           else
              fprintf('No data in choosen image file \n');   
           end;
        end;   
elseif command == 2 
	% disp('h(2) selected.') 
	ImgNo = round(get(h(1),'value'));
	ImgNo = ImgNo + 1;
	if ImgNo > get(h(1),'Max')
	   ImgNo = get(h(1),'Max');
	end;   
	set(txt1,'string',num2str(ImgNo)); 
	set(h(1),'value',ImgNo); 
	FrameNo = round(get(h(15),'value'));

	ImageName = get(gcf,'name');
        if (isempty(ImageName)),
           fprintf('No image file selected\n');
        else   
           [precision,dim,siz,limits,scale,offset]=ReadAnalyzeHdr(ImageName);
           img=ReadAnalyzeImg(ImageName,dim,precision,limits,[ImgNo FrameNo]);
           if (~isempty(img)),
	      hhh=get(gca,'Children');
	      hh_image=-1;
	      for ii=1:length(hhh),
	         if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	            hh_image=hhh(ii);
	         end;   
	      end;
	      
	      if (hh_image ~= -1),
                 if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                    img=img;
		 else
                    img=img*scale-offset;
	         end;   
                 set(hh_image,'CData',rot90(img));
              end;   
           else
              fprintf('No data in choosen image file\n');   
           end;
        end;   
elseif command == 3 
	% disp('h(3) selected.') 
	ImgNo = round(get(h(1),'value'));
	ImgNo = ImgNo - 1;
	if ImgNo < get(h(1),'Min')
	   ImgNo = get(h(1),'Min');
	end;   
	set(txt1,'string',num2str(ImgNo)); 
	set(h(1),'value',ImgNo); 
	FrameNo = round(get(h(15),'value'));

	ImageName = get(gcf,'name');
        if (isempty(ImageName)),
           fprintf('No image file selected\n');
        else   
           [precision,dim,siz,limits,scale,offset]=ReadAnalyzeHdr(ImageName);
           img=ReadAnalyzeImg(ImageName,dim,precision,limits,[ImgNo FrameNo]);
           if (~isempty(img)),
	      hhh=get(gca,'Children');
	      hh_image=-1;
	      for ii=1:length(hhh),
	         if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	            hh_image=hhh(ii);
	         end;   
	      end;
	      
	      if (hh_image ~= -1),
                 if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                    img=img;
		 else
                    img=img*scale-offset;
	         end;   
                 set(hh_image,'CData',rot90(img));
              end;   
           else
              fprintf('No data in choosen image file\n');   
           end;
        end;   
elseif command == 4 
        % exit
        close(gcf);
	% disp('h(4) selected.') 
elseif command == 5 
	% disp('h(5) selected.') 
elseif command == 51 
	% disp('h5(1) selected.') 
	
        [ImageName,pathname] = uigetfile('*.img','Choose image file');
 
        if (ImageName ~= 0) & (~isempty(ImageName))
           eval(['cd ' pathname]);
           PointPos=strfind(ImageName,'.img');
           ImageName=ImageName(1:PointPos-1);
        
      	   set(gcf,'name',ImageName);
           [precision,dim,siz,limits,scale,offset]=ReadAnalyzeHdr(ImageName);
           img=ReadAnalyzeImg(ImageName,dim,precision,limits,[1 1]);
           if (isstr(get(gca,'UserData')) == 1) &...
		 (strcmp(get(gca,'UserData'),'ImageObject') == 1)
              hc=get(gca,'Children');
              for ii=1:length(hc),
                 delete(hc(ii));
              end;   
           end;
           % Delete any ROI definitions
           h_roi=get(gcf,'Children');
           for ii=1:length(h_roi)
              if (isstr(get(h_roi(ii),'UserData')) == 1) &...
		 (~isempty(strfind(get(h_roi(ii),'UserData'),'Roi'))),
                 delete(h_roi(ii));
              end;
           end;
           h_roi=get(h(9),'Children');
           for ii=1:length(h_roi)
              if (strcmp(get(h_roi(ii),'Label'),'Save img') == 1),
                 set(h_roi(ii),'UserData','h9(3)');
              end;
           end;
        
           if (~isempty(img)),
              if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                 img=img;
	      else
                 img=img*scale-offset;
              end;   

              % CS, 240594, Changed to allow more space for text
              if (isstr(get(gca,'UserData')) == 1) &...
		    (strcmp(get(gca,'UserData'),'ImageObject') ~= 1)
                 axes('position',[0.2 0.1 0.75 0.8],'DrawMode','fast');
              end;
              hi=imagesc(rot90(img));

              if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                 set(hi,'UserData',[limits(2) limits(1)]);
		 set(gca,'CLim',[limits(2) limits(1)]);
              else
                 set(hi,'UserData',[limits(2)*scale limits(1)*scale]);
		 set(gca,'CLim',[limits(2)*scale limits(1)*scale]);
              end;   

              colorbar
              set(gcf,'NextPlot','add');
           
              % CS, 240594, Changed to times font 
   	      set(gca,'UserData','ImageObject','TickDir','out','FontName','Times');
              axis('image');
              load ShowImageColMap.txt   % Definerer 64 colours efter SPM
              colormap(ShowImageColMap);
           else
              fprintf('No data in choosen image file (%s)\n',ImageName);   
           end;

	   if (get(h(1),'Min') == dim(3))
              set(h(1),'Max',dim(3)+1e-6);
	   else
              set(h(1),'Max',dim(3));
	   end  
           set(txt2,'String',num2str(dim(3)),'UserData',num2str(dim(3)));
	   set(txt1,'string','1'); 
	   set(h(1),'value',1); 

	   if (length(dim) == 3)
	     dim(4)=1;
	   end;  
	   if (get(h(15),'Min') == dim(4))
              set(h(15),'Max',dim(4)+1e-6);
	   else
              set(h(15),'Max',dim(4));
	   end  
           set(txt6,'String',num2str(dim(4)),'UserData',num2str(dim(4)));
	   set(txt5,'string','1'); 
	   set(h(15),'value',1); 
	   
           % CS, 240594, Changed to axis off
	   set(gca,'Visible','off');
	end;   
	
elseif command == 6
        % do nothing but show submenus (automatic)
	% disp('h(6) selected.')
elseif command == 61
        if (nargin == 1),
           % do nothing but show subsubmenus (automatic)
   	   % disp('h6(1) selected.')
   	else
	   if (isstr(get(gca,'UserData')) == 1) &...
		 (strcmp(get(gca,'UserData'),'ImageObject') == 1)
	      if param1 == 1,
	         % disp('h61(1) selected.')
   	         set(gca,'Visible','on');
	      elseif param1 == 2,
	         % disp('h61(2) selected.')
	         set(gca,'Visible','off');
   	      end;
   	   end;
   	end;         
elseif command == 62
        if (nargin == 1),
           % do nothing but show subsubmenus (automatic)
   	   % disp('h6(2) selected.')
   	else
	   if (isstr(get(gca,'UserData')) == 1) &...
		 (strcmp(get(gca,'UserData'),'ImageObject') == 1)
	      if param1 == 1,
	         % disp('h62(1) selected.')
	         LimX=get(gca,'XLim');
	         LimY=get(gca,'YLim');
	         DifX=LimX(2)-LimX(1);
	         XTxt=[LimX(1)-0.03*DifX,LimX(2)+0.03*DifX]; 
	         DifY=LimY(2)-LimY(1);
	         YTxt=[LimY(1)-0.03*DifY,LimY(2)+0.03*DifY];
	         h=text(XTxt,YTxt,'.'); 
	         set(h,'UserData','SlideMarkers');
	      elseif param1 == 2,
	         % disp('h62(2) selected.')
	         hhh=get(gca,'Children');
	         for ii=1:length(hhh),
	            if (isstr(get(hhh(ii))) == 1) &...
		       (strcmp(get(hhh(ii),'UserData'),'SlideMarkers') == 1)
	               delete(hhh(ii));
	            end;   
	         end;
	      end;
	   end; 
	end;           
elseif command == 63
        % do nothing but show subsubmenus (automatic)
        if (nargin == 1),
   	   % disp('h6(3) selected.')
   	else
	   h=get(gcf,'Children');
	   for i=1:length(h)
         if (isstr(get(h(i),'UserData')) == 1) &...
               (strcmp(get(h(i),'UserData'),'ImageObject') == 1)
	       h_ax_i=h(i);
	     end;
	   end;
	   axes(h_ax_i);
	   if (isstr(get(gca,'UserData')) == 1) &...
		 (strcmp(get(gca,'UserData'),'ImageObject') == 1)
	      if param1 == 1,
	         % disp('h63(1) selected.')
                 load ShowImageColMap.txt   % Definerer 64 colours efter SPM
                 colormap(ShowImageColMap)
	      elseif param1 == 2,
	         % disp('h63(2) selected.')
                 colormap(gray(64))
	      elseif param1 == 3,
	         % disp('h63(2) selected.')
                 colormap(hsv(64))
	      elseif param1 == 4,
	         % disp('h63(2) selected.')
                 colormap(hot(64))
	      elseif param1 == 5,
	         % disp('h63(2) selected.')
                 colormap(cool(64))
	      elseif param1 == 6,
	         % disp('h63(2) selected.')
                 colormap(pink(64))
	      elseif param1 == 7,
	         % disp('h63(2) selected.')
                 colormap(flipud(colormap))
	      end;
	   end;
   	end;   
elseif command == 64
        % Visble on/off
        if (nargin == 1),
   	   % disp('h6(4) selected.')
   	else
	   if param1 == 1,
	      for ii=1:length(handle_list);
	         if ((ii ~= 5) & (ii ~= 6) & (ii ~= 7) & (ii ~= 8)),
	            set(handle_list(ii),'Visible','on');
	         end;   
	      end;
	   elseif param1 == 2,
	      for ii=1:length(handle_list);
	         if ((ii ~= 5) & (ii ~= 6) & (ii ~= 7) & (ii ~= 8)),
	            set(handle_list(ii),'Visible','off');
	         end;   
	      end;
	   end;
        end;
elseif command == 65
        % change colormap manual
        if (nargin == 1),
   	   % disp('h6(5) selected.')
   	else
           h_txt = uicontrol(...
		'BackgroundColor',[ .7 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImageColorFcn();',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','left',... 
		'Units','normalized',... 
		'Position',[ 0.03 0.70 0.11 0.05 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'Style','edit',...
		'UserData','ColorbarVal'); 
	   if param1 == 1,  % Min value
	      set(h_txt,'CallBack','ShowImageColorFcn(1);');
	   elseif param1 == 2,
	      set(h_txt,'CallBack','ShowImageColorFcn(2);');
	   end;
	end;   
        
elseif command == 7
        % do nothing but show submenus (automatic)
	% disp('h(7) selected.')
elseif command == 71
        h_txt = uicontrol(...
		'BackgroundColor',[ .7 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImageTxtFcn(0);',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Units','normalized',... 
		'Position',[ 0.03 0.70 0.11 0.05 ],... 
		'Enable','on',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'Style','edit',...
		'UserData','h_WriteTxt'); 
elseif command == 72
        % do nothing but show subsubmenus (automatic)
        if (nargin == 1),
   	   % disp('h7(2) selected.')
   	else
   	   % disp('h72(?) selected.')
   	   h=get(h(7),'Children');
   	   for ii=1:length(h),
   	      if (strcmp(get(h(ii),'Label'),'Size') == 1)
   	         h_size = h(ii);
   	      end;
   	   end;
   	   if param1 == 1,
   	      set(h_size,'UserData','ON,8');
   	   elseif param1 == 2,
   	      set(h_size,'UserData','ON,12');
   	   elseif param1 == 3,
   	      set(h_size,'UserData','ON,24');
   	   elseif param1 == 4,
              h_txt = uicontrol(...
		'BackgroundColor',[ .7 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImageTxtFcn(2);',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','center',... 
		'Position',[ 0.03 0.70 0.11 0.05 ],... 
		'Enable','on',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'Style','edit',...
		'UserData','h_SizeTxt'); 
           end;
        end;         
elseif command == 73
        % do nothing but show subsubmenus (automatic)
        if (nargin == 1),
   	   % disp('h7(3) selected.')
   	else
   	   % disp('h73(?) selected.')
   	   h=get(h(7),'Children');
   	   for ii=1:length(h),
   	      if (strcmp(get(h(ii),'Label'),'Size') == 1)
   	         h_size = h(ii);
   	      end;
   	      if (strcmp(get(h(ii),'Label'),'Font') == 1)
   	         h_font = h(ii);
   	      end;
   	   end;
   	   set(h_size,'UserData','FONT');
   	   if param1 == 1,
   	      set(h_font,'UserData','Helvetica');
   	   elseif param1 == 2,
   	      set(h_font,'UserData','Times');
   	   elseif param1 == 3,
   	      set(h_font,'UserData','Courier');
   	   elseif param1 == 4,
   	      set(h_font,'UserData','Symbol');
   	   end;
   	end;   
elseif command == 74
        % do nothing but show subsubmenus (automatic)
        if (nargin == 1),
   	   % disp('h7(4) selected.')
   	else
   	   % disp('h74(?) selected.')
   	   h=get(h(7),'Children');
   	   for ii=1:length(h),
   	      if (strcmp(get(h(ii),'Label'),'Size') == 1)
   	         h_size = h(ii);
   	      end;
   	      if (strcmp(get(h(ii),'Label'),'Color') == 1)
   	         h_font = h(ii);
   	      end;
   	   end;
   	   set(h_size,'UserData','COLOR');
   	   if param1 == 1,
   	      set(h_font,'UserData','white');
   	   elseif param1 == 2,
   	      set(h_font,'UserData','red');
   	   elseif param1 == 3,
   	      set(h_font,'UserData','yellow');
   	   elseif param1 == 4,
   	      set(h_font,'UserData','green');
   	   elseif param1 == 5,
   	      set(h_font,'UserData','blue');
   	   end;
   	end;   
elseif command == 75
   	% disp('h7(4) selected.')
   	h=get(h(7),'Children');
   	for ii=1:length(h),
   	   if (strcmp(get(h(ii),'Label'),'Size') == 1)
   	      h_size = h(ii);
   	   end;
   	end;
   	set(h_size,'UserData','OFF');
elseif command == 76
   	% disp('h7(5) selected.')
   	h=get(h(7),'Children');
   	for ii=1:length(h),
   	   if (strcmp(get(h(ii),'Label'),'Size') == 1)
   	      h_size = h(ii);
   	   end;
   	end;
   	set(h_size,'UserData','DELETE');
elseif command == 8
        % do nothing but show submenus (automatic)
	% disp('h(8) selected.')
elseif command == 81
        orient landscape
	ImgNo = round(get(h(1),'value'));
	h=get(gcf,'Children');
	for i=1:length(h)
	  if (isstr(get(h(i),'UserData')) == 1) &...
		(strcmp(get(h(i),'UserData'),'ImageObject') == 1)
	    h_ax_i=h(i);
	  end;
	end; 
        h=text(mean(get(h_ax_i,'XLim')),...
               min(get(h_ax_i,'YLim'))-0.1*mean(get(h_ax_i,'YLim')),...
               ['Filename: ' get(gcf,'Name') ', Slice: ' num2str(ImgNo)],...
	       'Interpreter','none');
        set(h,'HorizontalAlignment','center');
        pos=get(gcf,'PaperPosition');
        marg=0.05*pos(3:4);
        siz=0.9*pos(3:4);
        set(gcf,'PaperPosition',[marg siz]); 
        print -dpsc
        set(gcf,'PaperPosition',pos); 
        delete(h);
elseif command == 82
        orient landscape
	ImgNo = round(get(h(1),'value'));
	h=get(gcf,'Children');
	for i=1:length(h)
	  if (isstr(get(h(i),'UserData')) == 1) &...
		(strcmp(get(h(i),'UserData'),'ImageObject') == 1)
	    h_ax_i=h(i);
	  end;
	end;  
	h=text(mean(get(h_ax_i,'XLim')),...
               min(get(h_ax_i,'YLim'))-0.1*mean(get(h_ax_i,'YLim')),...
               ['Filename: ' get(gcf,'Name') ', Slice: ' num2str(ImgNo)],...
	       'interpreter','none');
        set(h,'HorizontalAlignment','center');
        pos=get(gcf,'PaperPosition');
        marg=0.05*pos(3:4);
        siz=0.9*pos(3:4);
        set(gcf,'PaperPosition',[marg siz]); 
        print -dcdjcolor -Ppj1
        set(gcf,'PaperPosition',pos); 
        delete(h);
elseif command == 83
        % fprintf('\nSorry, Tiff image not implemented yet\n');
	h=get(gcf,'Children');
	for i=1:length(h)
	  if (isstr(get(h(i),'UserData')) == 1) &...
		(strcmp(get(h(i),'UserData'),'ImageObject') == 1)
	    h_ax_i=h(i);
	  end;
	end;
	axes(h_ax_i);
	hhh=get(gca,'Children');
	CLim=get(gca,'CLim');
	hh_image=-1;
	for ii=1:length(hhh),
	   if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	      hh_image=hhh(ii);
	   end;   
	end;
	if (hh_image ~= -1)
	   img=get(hh_image,'CData');
	   col=colormap;
	   name_1=get(gcf,'Name');
	   Stop=0;
	   i=1;
	   while (Stop == 0)
	      name=sprintf('%s_%i',name_1,i);
	      if (exist([name '.tif']) ~= 2)
	         Stop = 1;
	      end;
	      i=i+1;
	   end;
           ll=length(col);

	   img=img.*(img>CLim(1))+ll*(img>CLim(2));
	   img=img-CLim(1);
	   img=img*ll/(CLim(2)-CLim(1));
	   tiffwrite(img,col,name);
   	   fprintf('Tiff image %s written\n',name);
   	else
   	   fprintf('Did not find any image in current figure\n',name);
	end;
elseif command == 84
        % fprintf('\nSorry, PS image not implemented yet\n');
	h=get(gcf,'Children');
	for i=1:length(h)
	  if (isstr(get(h(i),'UserData')) == 1) &...
		(strcmp(get(h(i),'UserData'),'ImageObject') == 1)
	    h_ax_i=h(i);
	  end;
	end;
	axes(h_ax_i);
	hhh=get(gca,'Children');
	hh_image=-1;
	for ii=1:length(hhh),
	   if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	      hh_image=hhh(ii);
	   end;   
	end;
	if (hh_image ~= -1)
	   img=get(hh_image,'CData');
	   col=colormap;
	   CLim=get(gca,'CLim');
	   name_1=get(gcf,'Name');
	   Stop=0;
	   i=1;
	   while (Stop == 0)
	      name=sprintf('%s_%i',name_1,i);
	      if (exist([name '.eps']) ~= 2)
	         Stop = 1;
	      end;
	      i=i+1;
	   end;
	   h=figure('Visible','off');
	   imagesc(img);
	   colormap(col);
	   set(gca,'CLim',CLim);
	   axis('square');
	   axis('off');
	   eval(['print -depsc ' name]);
	   delete(h);
   	   fprintf('eps image %s written\n',name);
   	else
   	   fprintf('Did not find any image in current figure\n',name);
	end;

elseif command == 85
        % fprintf('\nSorry, Tiff image not implemented yet\n');
	h=get(gcf,'Children');
	for i=1:length(h)
	  if (isstr(get(h(i),'UserData')) == 1) &...
		(strcmp(get(h(i),'UserData'),'ImageObject') == 1)
	    h_ax_i=h(i);
	  end;
	end;
	axes(h_ax_i);
	hhh=get(gca,'Children');
	hh_image=-1;
	for ii=1:length(hhh),
	   if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	      hh_image=hhh(ii);
	   end;   
	end;
	
	Colormap=get(gcf,'Colormap');
        [NoOfColors,dummy]=size(Colormap);
        ImgLimits=get(hh_image,'UserData');
        Name=get(gcf,'Name');
	CLim=get(gca,'CLim');
     
  	[pre,dim,siz,lim,scale,offset]=ReadAnalyzeHdr(Name);
	
	if (hh_image ~= -1)

	   for ImgNo=1:dim(3)
	     
              img=ReadAnalyzeImg(Name,dim,pre,lim,ImgNo);
              if (~isempty(img)),
	         hhh=get(gca,'Children');
	         hh_image=-1;
	         for ii=1:length(hhh),
	            if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	               hh_image=hhh(ii);
	            end;   
	         end;
	      
	         if (hh_image ~= -1),
                    if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                       img=img;
                    else
                       img=img*scale-offset;
                    end;   
		    img=rot90(img);
                 end;   
              else
                 fprintf('No data in choosen image file\n');   
                 return;
	      end;

	  
	      name=sprintf('%s_sl%i',Name,ImgNo);
              ll=length(Colormap);
	      img=img.*(img>CLim(1))+ll*(img>CLim(2));
	      img=img-CLim(1);
	      img=img*ll/(CLim(2)-CLim(1));
	      tiffwrite(img,Colormap,name);
   	      fprintf('Tiff image %s written\n',name);
	   end;
	   
   	else
   	   fprintf('Did not find any image in current figure\n',name);
	end;
	
        
elseif command == 9
        % do nothing but show submenus (automatic)
	% disp('h(9) selected.')
	        
elseif command == 91
        % Create ROI
	% disp('h9(1) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        ShowImageRoiFcn;
elseif command == 92
        % Filter Inside
	% disp('h9(2) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        ShowImageRoiFcn(4,0);
elseif command == 93
        % Filter Outside
	% disp('h9(3) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        ShowImageRoiFcn(4,1);
elseif command == 94
        % BW one Inside
	% disp('h9(2) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        ShowImageRoiFcn(4,2);
elseif command == 95
        % BW zero Outside
	% disp('h9(3) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        ShowImageRoiFcn(4,3);
elseif command == 96
        % Save Image
	% disp('h9(6) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');

        h_roi=get(h(9),'Children');
   	for ii=1:length(h_roi),
   	   if (strcmp(get(h_roi(ii),'Label'),'Save img') == 1)
   	      h_save = h_roi(ii);
   	   end;
   	end;
   	
        if (isstr(get(h_save,'UserData')) == 1) &...
	      (strcmp(get(h_save,'UserData'),'h9(3)') == 1), 
   	   ShowImageRoiFcn(5,round(get(h(1),'value')),h_save);
	else
	   ShowImageRoiFcn(6,round(get(h(1),'value')));
	end;     
elseif command == 97
        % Filter/save all images
	% disp('h9(5) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');

        h_roi=get(h(9),'Children');
   	for ii=1:length(h_roi),
   	   if (strcmp(get(h_roi(ii),'Label'),'Save img') == 1)
   	      h_save = h_roi(ii);
   	   end;
   	end;
   	
        if (isstr(get(h_save,'UserData')) == 1) &...
	      (strcmp(get(h_save,'UserData'),'h9(3)') == 1), 
   	   ShowImageRoiFcn(14,round(get(h(1),'value')),h_save);
	else
	   ShowImageRoiFcn(15,round(get(h(1),'value')));
	end;     
elseif command == 98
        % Generate dynamic roi curve from marked ROI's and svae in file
	% disp('h9(6) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        
	ShowImageRoiFcn(16,get(gcf,'Name'));
elseif command == 99
        % Delete ROI
	% disp('h9(7) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
	   
        %set(gcf,'Pointer','crosshair');
        set(gcf,'Pointer','watch');
	ShowImageRoiFcn(7);
	set(gcf,'WindowButtonDownFcn','');
	% set(gcf,'WindowButtonDownFcn','ShowImageRoiFcn(7);');
	set(gcf,'WindowButtonUpFcn','');
	set(gcf,'WindowButtonMotionFcn','');
elseif command == 910
        % Mean/Std in ROI
	% disp('h9(8) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
	   
        %set(gcf,'Pointer','crosshair');
	%set(gcf,'WindowButtonDownFcn','ShowImageRoiFcn(9);');
        set(gcf,'Pointer','watch');
	ShowImageRoiFcn(9);
	set(gcf,'WindowButtonUpFcn','');
	set(gcf,'WindowButtonMotionFcn','');
elseif command == 911
        % Save ROI
	% disp('h9(9) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
	   
        %set(gcf,'Pointer','crosshair');
	%set(gcf,'WindowButtonDownFcn','ShowImageRoiFcn(10);');
        set(gcf,'Pointer','watch');
	ShowImageRoiFcn(10);
	set(gcf,'WindowButtonUpFcn','');
	set(gcf,'WindowButtonMotionFcn','');
elseif command == 912
        % Load ROI
	% disp('h9(10) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
	   
	set(gcf,'WindowButtonDownFcn','');
	set(gcf,'WindowButtonUpFcn','');
	set(gcf,'WindowButtonMotionFcn','');
	ShowImageRoiFcn(13);
	
elseif command == 10
        % do nothing but show submenus (automatic)
	% disp('h(10) selected.')
elseif command == 101
	% disp('h10(1) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        
        if (nargin == 1),
   	   % disp('h10(1) selected.')
   	else
   	   if (param1 ~= 0)
              ShowImageFilterFcn(1,param1);
           else   
              h_txt = uicontrol(...
		'BackgroundColor',[ .7 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImageFilterFcn(1,0);',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','left',... 
		'Position',[ 0.03 0.70 0.11 0.05 ],... 
		'Enable','on',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'Style','edit',...
		'UserData','h_SizeFilter'); 
           end;
        end;   
elseif command == 102
	% disp('h10(2) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        
        if (nargin == 1),
   	   % disp('h10(2) selected.')
   	else
   	   if (param1 ~= 0)
              ShowImageFilterFcn(2,param1);
           else   
              h_txt = uicontrol(...
		'BackgroundColor',[ .7 0 0 ],... 
		'ButtonDownFcn','',... 
		'CallBack','ShowImageFilterFcn(2,0);',... 
		'ForegroundColor',[ 0 0 0 ],... 
		'HorizontalAlignment','left',... 
		'Position',[ 0.03 0.70 0.11 0.05 ],... 
		'Enable','on',... 
		'Units','normalized',... 
		'Visible','on',... 
		'Clipping','on',... 
		'Interruptible','off',... 
		'Selected','off',... 
		'Style','edit',...
		'UserData','h_SizeFilter'); 
           end;
        end;   
elseif command == 103
	% disp('h10(3) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        % Filter all images in image file

        ShowImageFilterFcn(3);

elseif command == 11
        % do nothing but show submenus (automatic)
	% disp('h(11) selected.')
elseif command == 111
	% disp('h11(1) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        % Filter all images in image file

        ShowImageCutFcn(0);
elseif command == 112
	% disp('h11(2) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        % Print sag/cor in tiff file

        ShowImageCutFcn(2);
elseif command == 113
	% disp('h11(3) selected.')
        % fprintf('\nSorry, NOT implemented YET\n');
        % Print sag/cor in eps file

        ShowImageCutFcn(3);
                
elseif command == 12
        % do nothing but show submenus (automatic)
	% disp('h(12) selected.')
elseif command == 121
        % 
	% disp('h(121) selected.')

        ShowImageSegmFcn(0);

elseif command == 13
        % do nothing but show submenus (automatic)
	% disp('h(13) selected.')
elseif command == 131
        % do nothing but show submenus (automatic)
	% disp('h(13) selected.')
        
        Name=get(gcf,'Name');
        if (length(Name) ~= 0)
           Colormap=get(gcf,'Colormap');
           set(gcf,'Pointer','watch');
   	   h=get(gcf,'Children');
	   for i=1:length(h)
         if (isstr(get(h(i),'UserData')) == 1) &...
               (strcmp(get(h(i),'UserData'),'ImageObject') == 1)
	       h_ax_i=h(i);
	     end;
	   end;
	   axes(h_ax_i);
           CLim=get(gca,'CLim');
	   
           [pre,dim,siz,limits,scale,offset]=ReadAnalyzeHdr(Name);
           img=zeros(dim(2),dim(1),1,dim(3));
           for i=1:dim(3),
              img_tmp=ReadAnalyzeImg(Name,dim,pre,limits,i);
	      img(:,:,1,i)=rot90(img_tmp);
           end;
           
           if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
              img=img;
           else
              img=img*scale-offset;
           end;   

           set(gcf,'Pointer','arrow');
                      
	   figure('position',[ 150 150 900 700 ],'resize','on'); 
           set(gcf,'Colormap',Colormap);
           set(gcf,'Name',Name);

           set(gcf,'Pointer','watch');

           hi=montage(img,Colormap);
           set(hi,'UserData',[limits(2) limits(1)]); 
	   set(hi,'CDataMapping','scaled');

           h_ax=get(hi,'Parent');
           set(h_ax,'position',[0.05 0.05 0.9 0.85],'DrawMode','fast');
           set(h_ax,'UserData',[limits(2) limits(1)]);   
	   set(h_ax,'visible','off');
	   set(h_ax,'CLim',CLim);
           % colorbar
           
           set(gcf,'Pointer','arrow');
        end;     
elseif command == 14
        % do nothing but show submenus (automatic)
	% disp('h(14) selected.')
elseif command == 141
        % do nothing but show submenus (automatic)
	% disp('h(14) selected.')
        
        ShowImageFuseFcn(0);
elseif command == 15 
	% disp('h(15) selected.') 
	ImgNo = round(get(h(1),'value'));

	FrameNo = round(get(h(15),'value'));
	set(txt5,'string',num2str(FrameNo)); 

	ImageName = get(gcf,'name');
        if (isempty(ImageName)),
           fprintf('No image file selected\n');
        else   
           [precision,dim,siz,limits,scale,offset]=ReadAnalyzeHdr(ImageName);
           img=ReadAnalyzeImg(ImageName,dim,precision,limits,[ImgNo FrameNo]);
           if (~isempty(img)),
	      hhh=get(gca,'Children');
	      hh_image=-1;
	      for ii=1:length(hhh),
	         if (strcmp(get(hhh(ii),'Type'),'image') == 1),
	            hh_image=hhh(ii);
	         end;   
	      end;
	      
	      if (hh_image ~= -1),
                 if (scale == 0) | (abs(scale) < 1e-10) | (abs(scale) > 1e10)
                    img=img;
                 else
                    img=img*scale-offset;
                 end;   
                 set(hh_image,'CData',rot90(img));
              end;   
           else
              fprintf('No data in choosen image file \n');   
           end;
        end;   

else 
	error('Error: ShowImage.m called with incorrect command.') 
end 

