function [cmapstr, n]=cmapsel(oldstr,oldmap)
% Standard dialog for colormap changing
load('ShowImageColMap.txt');
  load('temperature.txt');  
  colormaps={'Edit Current' 'editcmap'; ...
	     'Invert Current' ''; ...
	     'ShowImageColMap' 'ShowImageColMap'; ...
	     'Temperature'   'temperature'; ...   
	     'gray'   'gray(64)'; ...
	     'bone'   'bone(64)';...
	     'pink'   'pink(64)'; ...
	     'copper' 'copper(64)'; ...
	     'spring' 'spring(64)'; ...
	     'summer' 'summer(64)'; ...
	     'autumn' 'autumn(64)'; ...
	     'winter' 'winter(64)'; ...
	     'hot'    'hot(64)'; ...
	     'cool'   'cool(64)'; ...
	     'hsv'    'hsv(64)'; ...
	     'prism'  'prism(64)'; ...
	     'flag'   'flag(64)'; ...
	     'Solid Red',     'repmat([1 0 0],64,1)'; ...
	     'Solid Green',   'repmat([0 1 0],64,1)'; ...
	     'Solid Blue',    'repmat([0 0 1],64,1)'; ...
	     'Solid Cyan',    'repmat([0 1 1],64,1)'; ...
	     'Solid Magenta', 'repmat([1 0 1],64,1)'; ...
	     'Solid Yellow',  'repmat([1 1 0],64,1)'; ...
	     'Other solid color', 'repmat(uisetcolor(''Set color''),64,1)'; ...
	    };
  [res, ok]=listdlg('ListString',colormaps(:,1),...
		    'SelectionMode','single',...
		    'Name','Select colormap');
  if ok
    cmapstr=colormaps{res,1};
    if strcmp(cmapstr,'Edit Current');
      lold=length(oldstr);
      if lold>9 & strcmp(oldstr(lold-8:lold),' - Edited')
	cmapstr=oldstr;
      else
	cmapstr=[oldstr ' - Edited'];
      end
      n=editcmap(oldmap);
      if isempty(n);
	n=oldmap;
	cmapstr=oldstr;
      end
    elseif strcmp(cmapstr,'Invert Current');
      lold=length(oldstr);
      if lold>9 & strcmp(oldstr(lold-8:lold),' - Inverted')
	cmapstr=oldstr;
      else
	cmapstr=[oldstr ' - Inverted'];
      end
      n=flipud(oldmap);
    else
      n=eval(colormaps{res,2});
    end
  else
    n=oldmap;
    cmapstr=oldstr;
  end
  