function frameGUI(h_mainfig,TaskIndex,varargin) 
% frameGUI update all frames in the GUI of the pipeline program.
%
% Input:
%   h_mainfig   : Handle to main figure of the pipeline program(mainGUI)
%   TaskIndex   : Index to active task in the project structure
%   varargin    : Abitrary number of input arguments. (NOT USED)
%
% Output:
%
% Uses special functions:
%____________________________________________
% M. Twadark and T. Dyrby, 010503, NRU
%SW version: 010603TD

figuresize=get(h_mainfig,'position');       %returns position & size [x y 400 300]

%____ Load data stored in mainfig
project=get(h_mainfig,'UserData');
data=project.handles.data;
leftframewidth=data.leftframewidth;
rightframewidth=data.rightframewidth;

%_____ Make infoframe
uicontrol('parent',h_mainfig,...
    'tag','infoFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[leftframewidth-20 figuresize(4)-431+20 2 212-20],...
    'BackgroundColor',[252/255 252/255 254/255]);   %infoframe rightline
uicontrol('parent',h_mainfig,...
    'tag','infoFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[20 figuresize(4)-431+20 2 210-20],...
    'BackgroundColor',[252/255 252/255 254/255]);    %infoframe leftline
uicontrol('parent',h_mainfig,...
    'tag','infoFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[20 figuresize(4)-431+210 161 2],...
    'BackgroundColor',[252/255 252/255 254/255]); %infoframe topline
uicontrol('parent',h_mainfig,...
    'tag','infoFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[20 figuresize(4)-431+20 160 2],...
    'BackgroundColor',[252/255 252/255 254/255]);    %infoframe bottomline
uicontrol('parent',h_mainfig,...
    'tag','infoFrame',...
    'units','pixels',...
    'style','text',...
    'fontsize',data.textsize,...
    'fontname','fixedwidth',...
    'String','Information',...   
    'position',[25 figuresize(4)-431+4+200 68 16],...
    'BackgroundColor',[252/255 252/255 254/255]); %infoframe title

%_____ Make Site window frame (right frame)
uicontrol('parent',h_mainfig,...
    'tag','resultFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[leftframewidth+rightframewidth 15+55+20+23 2 figuresize(4)-108-20-23],...
    'BackgroundColor',[252/255 252/255 254/255]);   %rightframe rightline
uicontrol('parent',h_mainfig,...
    'tag','resultFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[leftframewidth 15+55+20+23 2 figuresize(4)-110-20-23],...
    'BackgroundColor',[252/255 252/255 254/255]);                   %rightframe leftline
uicontrol('parent',h_mainfig,...
    'tag','resultFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[leftframewidth (figuresize(4)-95+15+40) rightframewidth 2],...
    'BackgroundColor',[252/255 252/255 254/255]);  %rightframe topline
uicontrol('parent',h_mainfig,...
    'tag','resultFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[leftframewidth 15+55+20+23 rightframewidth 2],...
    'BackgroundColor',[252/255 252/255 254/255]);          %rightframe bottomline
uicontrol('parent',h_mainfig,...
    'tag','resultFrame',...
    'style','text',...
    'fontsize',data.textsize,...
    'fontname','fixedwidth',...
    'String','Display',...
    'units','pixels',...
    'position',[leftframewidth+10 figuresize(4)-45 54 14],...
    'BackgroundColor',[252/255 252/255 254/255]); %rightframe title 

%_____ Make Method frame (left frame)
uicontrol('parent',h_mainfig,...
    'tag','methodFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[leftframewidth-15 15+55+20+23 2 figuresize(4)-108-20-23],...
'BackgroundColor',[252/255 252/255 254/255]);    %leftframe rightline
uicontrol('parent',h_mainfig,...
    'tag','methodFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[15 15+55+20+23 2 figuresize(4)-108-20-23],...
    'BackgroundColor',[252/255 252/255 254/255]);                   %leftframe leftline
uicontrol('parent',h_mainfig,...
    'tag','methodFrame',...
    'style','frame',...
    'units','pixels',...
    'position',[15 (figuresize(4)-95+15+40) leftframewidth-30 2],...
    'BackgroundColor',[252/255 252/255 254/255]);%leftframe topline
uicontrol('parent',h_mainfig,...
    'tag','methodFrame',...
    'style','frame'...
    ,'units','pixels',...
    'position',[15 15+55+20+23 leftframewidth-30 2],...
    'BackgroundColor',[252/255 252/255 254/255]);                   %leftframe bottomline
uicontrol('parent',h_mainfig,...
    'tag','methodFrame',...
    'style','text',...
    'String','Method',...
    'fontsize',data.textsize,...
    'fontname','fixedwidth',...
    'units','pixels',...
    'position',[25 figuresize(4)-45 54 14],...
    'BackgroundColor',[252/255 252/255 254/255]);        %leftframe title

%_____ Make Logbar frame

%_____ Update topline below taskbuttons
set(findobj('tag','TopLine'),...
    'position',[5 figuresize(4)-28 leftframewidth+rightframewidth+10 1])

