function ColormapMenu

Press=get(gcf,'SelectionType');
switch Press
    case 'open'

        Data = get(gca,'userdata');

        load('ShowImageColMap.txt');
        load('temperature.txt');
        colormaps={'ShowImageColMap' 'ShowImageColMap'; ...
            'Temperature'   'temperature'; ...
            'gray'   'gray'; ...
            'bone'   'bone';...
            'pink'   'pink'; ...
            'copper' 'copper'; ...
            'spring' 'spring'; ...
            'summer' 'summer'; ...
            'autumn' 'autumn'; ...
            'winter' 'winter'; ...
            'hot'    'hot'; ...
            'cool'   'cool'; ...
            'hsv'    'hsv'; ...
            'prism'  'prism'; ...
            'flag'   'flag'; ...
            'Solid Red',     'repmat([1 0 0],64,1)'; ...
            'Solid Green',   'repmat([0 1 0],64,1)'; ...
            'Solid Blue',    'repmat([0 0 1],64,1)'; ...
            'Solid Cyan',    'repmat([0 1 1],64,1)'; ...
            'Solid Magenta', 'repmat([1 0 1],64,1)'; ...
            'Solid Yellow',  'repmat([1 1 0],64,1)'; ...
            'Other solid color', 'repmat(uisetcolor(c(1,:),''Set color''),64,1)'; ...
            };
        [res, ok]=listdlg('ListString',colormaps(:,1),...
            'SelectionMode','single',...
            'Name','Select colormap');
        if ok
            c=colormap;
            n=eval(colormaps{res,2});
            if size(n)==[64 3]
                colormap(gca,n);
            end
        end

    case 'alt'
        lim=get(findobj(gcf,'type','axes','tag','roll'),'clim');
        res={};
        prompt={'Min','Max'};
        name='Enter limits for colormap:';
        numlines=1;
        defaultanswer={num2str(lim(1)), num2str(lim(2))};
        res=inputdlg(prompt,name,numlines,defaultanswer);
        if ~isempty(res)
            scbNewLim=[str2num(res{1}) str2num(res{2})];
            set(findobj(gcf,'type','axes'),'clim',scbNewLim);
%            set(findobj('type','axes','tag','roll'),'clim',scbNewLim);
            set(gca,'XAxisLocation','bottom');
        end
end

