function fig = roifig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load roifig

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'NumberTitle','off', ...
	'Position',[415 910 327 50], ...
	'Tag','Fig2');
h1 = uimenu('Parent',h0, ...
	'Label','&File', ...
	'Tag','&File1');
h2 = uimenu('Parent',h1, ...
	'Label','&Load...', ...
	'Tag','&FileLoad1');
h2 = uimenu('Parent',h1, ...
	'Label','&Save', ...
	'Separator','on', ...
	'Tag','&File&Save1');
h2 = uimenu('Parent',h1, ...
	'Label','Save &As...', ...
	'Tag','&FileSave &As1');
h1 = uimenu('Parent',h0, ...
	'Label','&Edit', ...
	'Tag','&Edit1');
h2 = uimenu('Parent',h1, ...
	'Label','&Select', ...
	'Tag','&Edit&Select1');
h2 = uimenu('Parent',h1, ...
	'Label','&Edit nodes', ...
	'Tag','&Edit&Edit nodes1');
h2 = uimenu('Parent',h1, ...
	'Label','&Copy', ...
	'Tag','&Edit&Copy1');
h2 = uimenu('Parent',h1, ...
	'Label','&Resize', ...
	'Tag','&Edit&Resize1');
h2 = uimenu('Parent',h1, ...
	'Label','&Delete', ...
	'Separator','on', ...
	'Tag','&Edit&Delete1');

h1 = uimenu('Parent',h0, ...
	'Label','&Draw', ...
	'Tag','&Draw1');
  h2 = uimenu('Parent',h1, ...
          'CallBackFcn','editroi(''draw'',''poly'')', ...
	  'Label','&Polygon', ...
	  'Tag','&Draw&Spline1');
  h2 = uimenu('Parent',h1, ...
          'CallBackFcn','editroi(''draw'',''ellipse'')', ...
	  'Label','&Ellipse', ...
	  'Tag','&Draw&Ellipse1');
  h2 = uimenu('Parent',h1, ...
          'CallBackFcn','editroi(''draw'',''contour'')', ...
	  'Label','&Contour', ...
	  'Tag','&Draw&Contour1');

h1 = uimenu('Parent',h0, ...
	'Label','&Mode', ...
	'Tag','&Mode1');
h2 = uimenu('Parent',h1, ...
	'Label','&Add', ...
	'Tag','&Mode&Add1');
h2 = uimenu('Parent',h1, ...
	'Label','&Remove', ...
	'Tag','&Mode&Remove1');
h2 = uimenu('Parent',h1, ...
	'Label','&Xor', ...
	'Tag','&Mode&Xor1');
h1 = uimenu('Parent',h0, ...
	'Label','&Options', ...
	'Tag','&Options1');
h2 = uimenu('Parent',h1, ...
	'Label','&Spline mode...', ...
	'Tag','&Options&Spline mode1');
h1 = uimenu('Parent',h0, ...
	'Label','&View', ...
	'Tag','&View1');
h2 = uimenu('Parent',h1, ...
	'Label','Zoom &In', ...
	'Tag','&ViewZoom &In1');
h2 = uimenu('Parent',h1, ...
	'Label','Zoom &Out', ...
	'Tag','&ViewZoom &Out1');
h2 = uimenu('Parent',h1, ...
	'Callback','editroi(''loadimg'')', ...
	'Label','&Load image...', ...
	'Separator','on', ...
	'Tag','&View&Load image...1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.701960784313725 0.701960784313725 0.701960784313725], ...
	'FontSize',16, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',mat1, ...
	'String','EDITROI', ...
	'Style','text', ...
	'Tag','StaticText1');
if nargout > 0, fig = h0; end
